Repository streamnative/pulsar-flink, pull requests merged in 2020-02, with the labels that each got.

#40 Move CI from internal jenkins to Github Action
  .github/workflows/pr.yaml
  Jenkinsfile
  precommit.sh
Labels: area/build

#45 Fix avro array read
  src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/PulsarDeserializer.java
  src/test/java/org/apache/flink/streaming/connectors/pulsar/FlinkPulsarTableITest.java
  src/test/java/org/apache/flink/streaming/connectors/pulsar/SchemaData.java
Labels: area/build

#48 Fix map deserialization
  src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/PulsarDeserializer.java
  src/test/java/org/apache/flink/streaming/connectors/pulsar/FlinkPulsarTableITest.java
  src/test/java/org/apache/flink/streaming/connectors/pulsar/SchemaData.java
Labels: workflow::in-review

#57 Enable auth for data streams
  README.md
  src/main/java/org/apache/flink/streaming/connectors/pulsar/FlinkPulsarRowSource.java
  src/main/java/org/apache/flink/streaming/connectors/pulsar/FlinkPulsarSinkBase.java
  src/main/java/org/apache/flink/streaming/connectors/pulsar/FlinkPulsarSource.java
  src/main/java/org/apache/flink/streaming/connectors/pulsar/PulsarTableSource.java
  src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/PulsarAdminUtils.java
  src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/PulsarMetadataReader.java
  src/main/java/org/apache/flink/table/catalog/pulsar/PulsarCatalog.java
  src/test/java/org/apache/flink/streaming/connectors/pulsar/FlinkPulsarITest.java
  src/test/java/org/apache/flink/streaming/connectors/pulsar/FlinkPulsarSourceTest.java
  src/test/java/org/apache/flink/streaming/connectors/pulsar/internal/CachedPulsarClientTest.java
  src/test/java/org/apache/flink/streaming/connectors/pulsar/testutils/TestMetadataReader.java
Labels: component/flink, type/enhancement

#60 flink checkpoint abort when source parallelism is greater than topic partition number
  src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/PulsarFetcher.java
Labels: type/bug
