Repository streamnative/pulsar-flink, pull requests merged in 2020-05, with the labels that each got.

#69 Update jackson-databind version to 2.10.1
  pom.xml
Labels: workflow::in-review

#76 add feature: enable earliest with external subscription mode
  src/main/java/org/apache/flink/streaming/connectors/pulsar/FlinkPulsarSource.java
Labels: type/feature

#83 Support build for scala-2.12
  .github/workflows/pr.yaml
  pom.xml
  precommit.sh
Labels: area/build
